[project]
name = "stack"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "luke-brous", email = "luke.broussard@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "jinja2>=3.1.6",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.1",
]

[project.scripts]
stack = "stack:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx2>=2.13.0",
    "pytest>=9.1.1",
]
